
- name: Install pre-requesites for dnf support for Fedora 29 and below
  raw: dnf install -y --allowerasing python-dnf
  when: ansible_distribution == 'Fedora' and ansible_distribution_version|int <= 29
  become: true

- name: Install pre-requesites for dnf support for Fedora 30 and above
  raw: dnf install -y --allowerasing python3-dnf
  when: ansible_distribution == 'Fedora' and ansible_distribution_version|int >= 30
  become: true

- name: Check if EPEL is installed for non Fedora distros
  shell: rpm -qa | grep epel-release
  register: epel_rpm
  ignore_errors: yes
  when: not ansible_distribution == 'Fedora'
  become: true

- name: Pull down the EPEL for for non Fedora distros
  get_url:
    url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    dest: "{{ ansible_env.HOME }}/epel-release-latest-7.noarch.rpm"
  when:
    - not ansible_distribution == 'Fedora'
    - epel_rpm.stdout == ""

- name: Install EPEL for non Fedora distros
  yum:
    name: "{{ ansible_env.HOME }}/epel-release-latest-7.noarch.rpm"
    state: present
  when:
    - not ansible_distribution == 'Fedora'
    - epel_rpm.stdout == ""
  become: true

- name: "Install libvirt, qemu-kvm, and jq on {{ ansible_distribution }}"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libvirt
    - qemu-kvm
    - jq
    - libselinux-python
    - git
  become: true
  when: not ansible_distribution == 'Fedora'

- name: "Install libvirt, qemu-kvm, and jq on {{ ansible_distribution }} version 29 or below"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libvirt
    - qemu-kvm
    - jq
    - libselinux-python
    - git
  become: true
  when: ansible_distribution == 'Fedora' and ansible_distribution_major_version|int <= 29

#- name: "Install libvirt, qemu-kvm, and jq on {{ ansible_distribution }} version 30 or above"
#  package:
#    name: "{{ item }}"
#    state: present
#  with_items:
#    - libvirt
#    - qemu-kvm
#    - jq
#    - python3-libselinux
#    - git
#  become: true
#  when: ansible_distribution == 'Fedora' and ansible_distribution_major_version|int >= 30
