---
# Install the kvm plugin
- name: Pull down kvm plugin
  get_url:
    url: https://github.com/dhiltgen/docker-machine-kvm/releases/download/{{ dkvm_version }}/docker-machine-driver-kvm-centos7
    dest: /usr/local/bin/docker-machine-driver-kvm
    mode: 755
  become: true

- import_tasks: install_virtual_reqs.yml

- name: Start and enable libvirtd
  service:
    name: libvirtd
    state: started
    enabled: yes
  become: true

- name: "Add user {{ user }} to the libvirt group"
  user:
    name: "{{ user }}"
    groups: libvirt
    append: yes
  become: true

- name: Newgroup libvirt
  user:
    name: libvirt
    state: present
  become: true