---
# tasks file for prereqs

# install necessary virtualization plugins
- name: Linux pre reqs setup
  block:
    - import_tasks: setup_nested_virt.yml
    - import_tasks: install_virtual_reqs.yml
    - import_tasks: install_kvm_plugin.yml
  when: host_os == "linux"

# install homebrew and brew packages
- name: Mac pre req setup
  import_tasks: install_mac_pre_reqs.yml
  when: host_os == "darwin"
