---
# Filter templates according to whitelist/blacklist rules (No filtering by default)

- name: "{{ container_config_name }} :: Get template name from the yaml file"
  shell: "{{ oc_bin }} process -f {{ template_file.path }} | jq '.items[1].metadata.labels.template' | sed 's/\"//g'"
  register: "template_name"

- name: "Template name"
  debug:
    msg: "Template name: {{ template_name.stdout }}"

- name: "Add to templates list if template name is in whitelist"
  set_fact:
    os_template_files: "{{ os_template_files|default([]) + [ template_file ] }}"
  when: (template_name.stdout in os_template_whitelist) and ((os_template_whitelist | default([])) | length != 0) and (template_name.stdout not in os_template_blacklist)

- name: "Add to templates list if template name is not in blacklist and whitelist isn't set"
  set_fact:
    os_template_files: "{{ os_template_files|default([]) + [ template_file ] }}"
  when: (template_name.stdout not in os_template_blacklist) and ((os_template_whitelist | default([])) | length == 0)
