---

# Start builds for each container defined in the template files
- name: "Start builds for containers defined in the template files - attempt {{ attempt_number }}"
  include_tasks: "build_new_app.yml template_name={{ template_filename.path }}.processed"
  with_items: "{{ os_templates.files }}"
  when: (total_build_success|bool == false)
  loop_control:
    loop_var: template_filename

# Check on build status of each container, finalize if done
- name: "Check on build status of containers, finalize if done - attempt {{ attempt_number }}"
  include_tasks: "check_new_app.yml template_name={{ template_filename.path }}.processed"
  with_items: "{{ os_templates.files }}"
  when: (total_build_success|bool == false)
  loop_control:
    loop_var: template_filename

- set_fact:
    total_build_success: true

# Check if all builds are marked as succesful
- name: "Check if all builds are marked as succesful"
  set_fact:
    total_build_success: "{{ total_build_success|bool and template_result.value|bool }}"
  with_dict: "{{ build_results }}"
  loop_control:
    loop_var: template_result
