---
# check if the minishift cluster is started if not then start the cluster

# check if minishift is already up and running
- name: "Check if the minishift profile is already up and running"
  shell: "{{ minishift_bin }} status --profile {{ profile }} | head -1 | awk '{print $2}'"
  register: minishift_status

# start minishift profile
- name: "Start minishift profile {{ profile }}"
  shell: "{{ minishift_bin }} start --profile {{ profile }} --cpus {{ cpus }} --disk-size {{ disk_size }} --memory {{ memory }} --openshift-version {{ oc_version }} --iso-url file:///{{ minishift_dest_dir }}/minishift.iso"
  when: minishift_status.stdout == "Stopped"
